DBCC CHECKIDENT ('dbo.Dish', RESEED, 1);

SET IDENTITY_INSERT [dbo].[Dish] ON
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (1, N'Aaloo ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (2, N'Pyaz ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (3, N'Shimla Mirch ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (4, N'Carrot Poriyal', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (5, N'Patta Gobhi (Yellow)', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (6, N'Phool Gobhi', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (7, N'Mogar', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (8, N'Mix. Veg Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (9, N'Gatte ki Sabji', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (10, N'Palak Paneer', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (11, N'Palak Tamatar', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (12, N'Ghiya', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (13, N'Bhindi Pyaaz', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (14, N'Bhindi ', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (15, N'Achari Bhindi', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (16, N'Achari Brocolli', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (17, N'Kumbh Hara Dhaniya', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (18, N'Kumbh Do Pyaaza', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (19, N'Methi Aaloo', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (20, N'Kadai Paneer', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (21, N'Tamatar Aaloo', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (22, N'Baingan Bharta', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (23, N'Chole ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (24, N'Chawle Ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (25, N'Dum Aaloo', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (26, N'Sarson Ka Saag', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (27, N'Aaloo Pyaz ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (28, N'Mangodi ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (29, N'Mooth ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (30, N'Soybean Ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (31, N'Karele ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (32, N'Kala Chane Ki Sabji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (33, N'Bhindi Fry', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (34, N'Stuffed Ghiya', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (35, N'Matar Mushroom', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (36, N'Aaloo Shimlamirch', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (37, N'Rataloo', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (38, N'Tindori', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (39, N'Matar Fry', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (40, N'Gawar Fali', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (41, N'Chole Salad', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (42, N'Mooth Salad', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (43, N'Moong Salad', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (44, N'Soybean Salad', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (45, N'Caprese', 6)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (46, N'Kala Chana Salad', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (47, N'Rajma Salad', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (48, N'Mixed Bean Salad', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (49, N'Boondi Raitha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (50, N'Pyaz Tamatar Raitha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (51, N'Cucumber Raitha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (52, N'Pineapple Raitha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (53, N'Carrot Raitha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (54, N'Aaloo Paratha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (55, N'Gobhi Paratha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (56, N'Paneer Paratha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (57, N'Methi Paratha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (58, N'Matar Paratha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (59, N'Palak Paratha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (60, N'Onion Rice', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (61, N'Kabuli', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (62, N'Toor Dal', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (63, N'Yellow Moong Dal', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (64, N'Green Moong Dal', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (65, N'Dal Hariyali', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (66, N'Dal Tadka', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (67, N'Dal Makhani', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (68, N'Red Masoor Dal', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (69, N'Black Masoor Dal', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (70, N'Kadhi', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (71, N'Rajma', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (72, N'Panchratani Dal', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (73, N'Pakistani Chana Dal', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (74, N'Dal Amritsari ', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (75, N'Pudhina Pulav', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (76, N'Curd Rice', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (77, N'Lemon Rice', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (78, N'Moong Dal Khichadi', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (79, N'Toor Dal Khichadi', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (80, N'Pongal', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (81, N'White Pulav', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (82, N'Aaloo Pyaz Pulav', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (83, N'Gobhi Matar Pulav', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (84, N'Bissis Bhela Bhaat', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (85, N'Jhatpat Biryani', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (86, N'Tomato Rice', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (87, N'Coconut Rice', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (88, N'Fried Rice', 2)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (89, N'Idly', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (90, N'Dosa', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (91, N'Sambhar', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (92, N'Utappam', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (93, N'Sambar Rice', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (94, N'Rasam with Rice', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (95, N'Red Sauce Pasta', 6)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (96, N'White Sauce Pasta', 6)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (97, N'Mix Sauce Pasta', 6)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (98, N'Pizza', 6)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (99, N'Grilled Sandwich', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (100, N'Sauted Paneer', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (101, N'Augratin', 4)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (102, N'Mushroom Macaroni', 6)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (103, N'Sauted Veggies w/ Dip', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (104, N'Baked Canaloni', 6)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (105, N'Pesto Pasta', 6)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (106, N'Tikki Rice', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (107, N'Sauted Baby Potatoes', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (108, N'Fruit & Veg. Salad', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (109, N'Bhel Puri', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (110, N'Sev Puri', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (111, N'Dahi Puri', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (112, N'Dabeli', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (113, N'Pav Bhaji', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (114, N'Vada Pav', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (115, N'Chola Tikki', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (116, N'Pani Patasha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (117, N'Aaloo Chat', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (118, N'Paneer Tikka', 10)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (119, N'Moong Dal Dhokli ', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (120, N'Besan Chilada', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (121, N'Green Moong Dal Chilada', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (122, N'Yellow Moong Dal Chilada', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (123, N'Veg. Frankie', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (124, N'Tacos', 9)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (125, N'Clear Veg Soup', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (126, N'Sweet Corn Soup', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (127, N'Cream of Spinach Soup', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (128, N'Brocolli Soup', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (129, N'Asparagus Soup', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (130, N'Lemon Coriander Soup', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (131, N'Mushroom Vermicilli Soup', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (132, N'Manchow Soup', 2)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (133, N'Palak Soup', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (134, N'Poha', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (135, N'Upma', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (136, N'Sabudana Khichadi', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (137, N'Oats', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (138, N'Cereals', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (139, N'Sevaiyaan', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (140, N'Bagani', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (141, N'Geela Khakra', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (142, N'Masala Moong', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (143, N'Masala Mooth', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (144, N'Rava Dhokla', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (145, N'Bread Toast', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (146, N'Sandwich', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (147, N'Veg. Daliya', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (148, N'Masala Idli', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (149, N'Khaman Dhokla', 13)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (150, N'Handwa', 13)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (151, N'Paneer Toast', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (152, N'Hashbrown Omlet', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (153, N'Bread Idli', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (154, N'Suji Bread', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (155, N'Suji Ka Halwa', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (156, N'Aate Ka Halwa', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (157, N'Badam Ka Halwa', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (158, N'Phirni', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (159, N'Sabudana Kheer', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (160, N'Sandesh', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (161, N'Faulda', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (162, N'Fruit Pudding', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (163, N'Makki Ki Ghaat', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (164, N'Baajre Ka Khichada', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (165, N'Gyehon Ka Kheechada', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (166, N'Gatte Ki Khichadi', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (167, N'Meetha Pulav', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (168, N'Dal Baati', 12)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (169, N'Mango Milk Shake', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (170, N'Strawberry Shake', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (171, N'Strawberry Banana Shake', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (172, N'Carrot Milk', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (173, N'Veg. Kurma', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (174, N'Patta Gobhi (White)', NULL)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (175, N'Patta Gobhi Poriyal', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (176, N'Beans Poriyal', 5)
INSERT INTO [dbo].[Dish] ([Id], [Name], [CuisineId]) VALUES (177, N'Toor Dal Dhokli', 13)
SET IDENTITY_INSERT [dbo].[Dish] OFF
